### ISSUE TITLE
question: Can I use standard Parity client for Ethereum?

### ISSUE THREAD

**Issue by EZS-JD** [energywebfoundation/energyweb-client#1]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.8.3-beta-b49c44a-20171114/x86_64-macos/rustc1.21.0
> - **Operating system**: MacOS 
> - **And installed**: homebrew

---

Can I use any Parity installation like the one in homebrew to run the ewf testnet Tobalaba? Is Tobalaba a private Ethereum chain?

**Comment by jbentke** [comment]
Yes you can run any parity above v1.8
