### ISSUE TITLE
Compiling app_dirs fails while building

### ISSUE THREAD

**Issue by oudsteyn** [energywebfoundation/energyweb-client#10]
**Operating system**: MacOS
**And installed**: from source
**Rust Version**: 1.25.0

Compiling app_dirs fails when running build command
`cargo build --release`

Error
```
error[E0619]: the type of this value must be known in this context
  --> /Users/john/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |    
```                                    ^^^^

**Comment by jbentke** [comment]
pushed the new version and tested it on my mac, please dont forget to update your rust with `rustup update`
