### ISSUE TITLE
faucet broken?

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/energyweb-client#18]
I have submitted my address to

* http://tobalaba.slock.it/faucet
* faucet@energyweb.org
* https://energyweb.org/contact-us/
* https://slock.it/contact.html

but:

```
./target/release/parity --chain tobalaba
geth attach ~/.local/share/io.parity.ethereum/jsonrpc.ipc

web3.eth.blockNumber
web3.fromWei(web3.eth.getBalance(web3.eth.accounts[0]),"ether")
```

> 4242702  
> 0

**Comment by drandreaskrueger** [comment]
and still empty almost a working day later:
```
web3.eth.blockNumber
4245168
```

**Comment by drandreaskrueger** [comment]
if all 4 mentioned recipients are on holidays ... who else can I ask for Tobalaba tokens?

**Comment by bytniak** [comment]
1) I'm not he admin here, but I can send you some tobalaba-testnet-ethers, just ping me your address. 
2) Currently the gas price in the network is almost 0, which means that you can issue free transactions, just set the gas price to 0, for your transactions. You can deploy smart contracts (like erc-20 token contract), interact with them (like sending erc-20 tokens around). You can't however send around and play with ethers (since you don't have any).

**Comment by drandreaskrueger** [comment]
@bytniak much appreciated. I have sent you a msg via your http://flexidao.com

**Comment by drandreaskrueger** [comment]
But IMHO someone should repair the faucet.

**Comment by drandreaskrueger** [comment]
I have just checked via https://tobalaba.etherscan.com - still nothing.

**Comment by drandreaskrueger** [comment]
I had tried the faucet 3 times before I gave up.   
Also, I recommend to energyweb.org & slock.it that they check & answer their message form. No answer to my messages from early this week.


Now tried faucet again, from 3 different browsers. Two seem to have gone through now.

Thanks!  
Sunny greetings  
Andreas

**Comment by drandreaskrueger** [comment]
Perhaps they are using javascript in their forms? And then fail silently when errors due to javascript blockers?
I got no error message whatsoever. --> Always also check your www stuff with "[ScriptSafe](https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf)"

**Comment by drandreaskrueger** [comment]
Something is different. All 3 requests to the faucet are going through now.

Thanks a lot.

CanClose.
