### ISSUE TITLE
Tobalaba in Docker

### ISSUE THREAD

**Issue by EZS-JD** [energywebfoundation/energyweb-client#2]
How can I run Tobalaba in Docker? Will this work?

https://hub.docker.com/r/parity/parity/

**Comment by jbentke** [comment]
You can run the parity docker container and pass the tobalaba chain specification as a parameter. The chain spec can be found here https://github.com/energywebfoundation/energyweb-client/blob/master/ethcore/res/ethereum/tobalaba.json

To pass the chain spec, add the command parameter `--chain /path/to/chain/spec` in your yml file.

**Comment by EZS-JD** [comment]
what about https://hub.docker.com/r/energywebfoundation/ewf-client/
Is it maintained?
