### ISSUE TITLE
Increase maximumUncleCount

### ISSUE THREAD

**Issue by bytniak** [energywebfoundation/energyweb-client#6]
> I'm running:
>
> - **Parity version**: 1.9.0
> - **Operating system**: Linux
> - **And installed**: from source

---
I think new parity release 1.9.0 by the default doesn't allow for uncles to occur and therefore preventing synchronization with the blockchain from block #2340601, where the first uncle occurs.
The solution for this issue is to add:

    "maximumUncleCount": 1

to the [tobalaba.json](https://github.com/energywebfoundation/energyweb-client/blob/master/ethcore/res/ethereum/tobalaba.json) file in the `"params: "` of the `"authorityRound: "`.

EDIT: Now increase to two is needed since block #2381455

    "maximumUncleCount": 2

**Comment by jbentke** [comment]
changed to high number as we dont want to hardfork currently
