### ISSUE TITLE
Parity not syncing Tobalaba blockchain

### ISSUE THREAD

**Issue by bkchaitra** [energywebfoundation/energyweb-client#7]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.9.4
> - **Operating system**: Windows
> - **And installed**:  from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---After successful build I get error, when i try to start parity with ,
$ ./target/release/parity --chain tobalaba

I get the following error

"unable to listen on 127.0.0.1:8546 WebSockets address 127.0.0.1:8546 is already in use, make sure that another instance of an Ethereum client is not running or change the address using the --ws-port and --ws-interface options."

**Comment by jbentke** [comment]
That means you already have a software running on the port 8546 (propably another ethereum client?) you can change the port of your websocket by using the `--ws-port` option when starting parity, for example `$ ./target/release/parity --chain tobalaba --ws-port 8547`

**Comment by bkchaitra** [comment]
Have tried that . still no luck.i have logged in as administrator

2018-03-07 07:04:38  State DB configuration: fast
2018-03-07 07:04:38  Operating mode: active
2018-03-07 07:04:38  Configured for Tobalaba using AuthorityRound engine
2018-03-07 07:04:38  Updated conversion rate to Ξ1 = US$788.61 (150958800 wei/gas)
2018-03-07 07:04:38  Network port V4(0.0.0.0:30303) is already in use, make sure that another instance of an Ethereum client is not running or change the port using the --port option.
Unable to create IPC directory at \\.\pipe\: A required privilege is not held by the client. (os error 1314)
